project:
  type: book

book:
  title: "An Instance-Based Account of Context Maintenance and Retrieval"
  lang: "en"
  execute: false
  chapters:
    - index.md
    - 00_Introduction.md
    - 01_Classic_CMR.md
    - 02_Instance_CMR.md
    - 03_Evaluation_Approach.md
    - 04_Baseline_Comparison.md
    - 05_Variable_List_Lengths.md
    - 06_Item_Repetitions.md
    - 07_Discussion.md
    - references.md
    - ../../reports/subjectwise_model_evaluation/Subjectwise_Model_Evaluation_Dual_Store_Murdock1962.ipynb

bibliography: ../references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    author: 
      - |
        | Jordan B. Gunn
        | Cognition and Cognitive Neuroscience Program
        | Vanderbilt University
        | Nashville, TN 37235
        | \texttt{jordan.gunn@vanderbilt.edu}
      - |
        | \textbf{Sean M. Polyn}
        | Department of Psychological Sciences
        | Vanderbilt University
        | Nashville, TN 37235
        | \texttt{sean.polyn@vanderbilt.edu}
    header-includes: |
      \usepackage{setspace}
      \onehalfspacing
      %\doublespacing
      \usepackage{arxiv}
    toc: false
    keep-tex: true
    echo: false
    output: false
    documentclass: article
    #classoption:  12pt