project:
  type: book

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    author: 
      - |
        | Jordan B. Gunn
        | Cognition and Cognitive Neuroscience Program
        | Vanderbilt University
        | Nashville, TN 37235
        | \texttt{jordan.gunn@vanderbilt.edu}
      - |
        | \textbf{Sean M. Polyn}
        | Department of Psychological Sciences
        | Vanderbilt University
        | Nashville, TN 37235
        | \texttt{sean.polyn@vanderbilt.edu}
    toc: false
    keep-tex: true
    echo: false
    output: false
    documentclass: scrreport
    header-includes: |
      %\usepackage{setspace}
      %\onehalfspacing
      %\doublespacing
      %\usepackage{arxiv}
    #classoption:  12pt

book:
  title: "An Instance-Based Account of Context Maintenance and Retrieval"
  lang: "en"
  execute: false
  chapters:
    - index.md
    - 01_Classic_CMR.md
    - 02_Instance_CMR.md
    - 03_Evaluation_Approach.md
    - 04_Baseline_Comparison.md
    - 05_Variable_List_Lengths.md
    - 06_Item_Repetitions.md
    - 07_Discussion.md
    - references.md
    - Subjectwise_Model_Evaluation_Dual_Store_Murdock1962.ipynb
  abstract: |
    In retrieved-context accounts of memory search like the Context Maintenance and Retrieval (CMR) model [@polyn2009context], representations of studied items in a free recall experiment are associated with states of an internal representation of temporal context that slowly evolves across the study period. These mechanisms enable models to account for organizational effects in recall sequences, such as the tendency for related items to be recalled successively. Retrieved context models tend to specify these dynamics in a simplified neural network that builds a single prototypical pattern of associations between each item and context (and vice versa) across experiences.  By contrast, models of categorization and other memory phenomena have increasingly converged on instance-based architectures @hintzman1984minerva. These conceptualize memory as a stack of trace vectors representing discrete experiences and supporting recall through parallel nonlinear activation based on similarity to a probe. To investigate the consequences of this distinction, we present an instance-based specification of CMR that encodes associations between studied items and context by instantiating memory traces corresponding to each experience and drives recall through context-based coactivation of those traces. We analyze the model's ability to account for traditional phenomena that have been used as support for the original prototypical specification of CMR, evaluate conditions under which the specifications might behave differently, and explore the model's capacity for integration with existing instance-based models to elucidate a broader collection of memory phenomena.
